# Welcome to Mago!
# For full documentation, see https://mago.carthage.software/tools/overview
php-version = "8.5.0"

[source]
paths = ["src/", "tests/"]
includes = ["vendor"]
excludes = []

[formatter]
print-width = 120
tab-width = 4
use-tabs = false
null-type-hint = "null_pipe"

[linter]
integrations = ["symfony", "laravel", "phpunit"]

[linter.rules]
# ambiguous-function-call = { enabled = false }
# literal-named-argument = { enabled = false }
# halstead = { enabled = false }
# interface-name = { enabled = false }
# kan-defect = { enabled = false }
# cyclomatic-complexity = { enabled = false }

[analyzer]
# find-unused-definitions = true
# find-unused-expressions = false
# analyze-dead-code = false
# check-throws = true
# allow-possibly-undefined-array-keys = true
# perform-heuristic-checks = true